---
name: MySQL-Admin
version: 0.43
author:
  - 'Dirk Lindner <lze@cpan.org>'
abstract: Admin
license: lgpl
resources:
  license: http://opensource.org/licenses/lgpl-license.php
requires:
  Authen::Captcha: '>=1.023'
  CGI: '>=3.29'
  DBI: '>=1.50'
  HTML::Menu::TreeView: '>=1.04'
  HTML::Parser: '>=3.56'
  MD5: '>=2.03'
  Mail::Sendmail: '>=0.79'
  Module::Build: '>=0.2808'
  Parse::BBCode: '>=0.08'
  Syntax::Highlight::Engine::Kate: '>=0.04'
  Syntax::Highlight::Perl: '>=1.00'
  Test::More: '>=0.7'
provides:
  CGI::QuickFormR:
    file: lib/CGI/QuickFormR.pm
    version: 1.93
  DBI::Library:
    file: lib/DBI/Library.pm
    version: 0.43
  DBI::Library::Database:
    file: lib/DBI/Library/Database.pm
    version: 0.43
  DBI::Library::Database::db:
    file: lib/DBI/Library/Database.pm
  DBI::Library::Database::st:
    file: lib/DBI/Library/Database.pm
  DBI::Library::db:
    file: lib/DBI/Library.pm
  DBI::Library::st:
    file: lib/DBI/Library.pm
  HTML::Editor:
    file: lib/HTML/Editor.pm
    version: 0.43
  HTML::Editor::BBCODE:
    file: lib/HTML/Editor/BBCODE.pm
    version: 0.43
  HTML::Menu::Pages:
    file: lib/HTML/Menu/Pages.pm
    version: 0.43
  HTML::TabWidget:
    file: lib/HTML/TabWidget.pm
    version: 0.43
  HTML::Window:
    file: lib/HTML/Window.pm
    version: 0.43
  MySQL::Admin:
    file: lib/MySQL/Admin.pm
    version: 0.43
  MySQL::Admin::Actions:
    file: lib/MySQL/Admin/Actions.pm
    version: 0.43
  MySQL::Admin::Config:
    file: lib/MySQL/Admin/Config.pm
    version: 0.43
  MySQL::Admin::GUI:
    file: lib/MySQL/Admin/GUI.pm
    version: 0.43
  MySQL::Admin::Main:
    file: lib/MySQL/Admin/Main.pm
    version: 0.43
  MySQL::Admin::Session:
    file: lib/MySQL/Admin/Session.pm
    version: 0.43
  MySQL::Admin::Settings:
    file: lib/MySQL/Admin/Settings.pm
    version: 0.43
  MySQL::Admin::Translate:
    file: lib/MySQL/Admin/Translate.pm
    version: 0.43
  Template::Quick:
    file: lib/Template/Quick.pm
    version: 0.43
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
